name: Test docs deployment

on:
  pull_request:
    branches: [develop]
    paths: 
      - 'docs/**'
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./docs
      - name: Copy changelog
        run: cp CHANGELOG.md docs/src/pages/changelog.md
      - name: Test build website
        run: yarn build
        working-directory: ./docs
